### ISSUE TITLE
error in the webapp-api

### ISSUE THREAD

**Issue by zramsay** [LaconicNetwork/issues#2] opened 2024-11-25 19:52 UTC
curl against the api endpoint within the webapp-deployer pod does not return anything.

```
curl http://localhost:9555 -k
curl: (52) Empty reply from server
```

**Comment by nikugogoi** [comment] 2024-11-26 07:13
Hi @zramsay 
Can you please share the following information:
- Chain endpoint config in webapp deployer
  ```bash
  # Run in the directory which contains the `webapp-deployer` deployment
  cat webapp-deployer/data/config/laconic.yml
  ```   
  
- Webapp deployer config
  ```bash
  cat webapp-deployer/config.env
  # Expected output
  # DEPLOYMENT_DNS_SUFFIX=""
  # ...
  ```

- Webapp deployer logs
  ```bash
  # Run in the directory which contains the `webapp-deployer` deployment
  laconic-so deployment --dir webapp-deployer ps

  # Expected output
  # id: default/laconic-817d3089c4c96d32-deployment-7d9ff577b6-5lpq2, name: laconic-817d3089c4c96d32-deployment-7d9ff577b6-5lpq2, ports: 10.42.2.11:9555->9555

  # Set pod ID
  export POD_ID=
  # Example:
  # export POD_ID=laconic-817d3089c4c96d32-deployment-7d9ff577b6-5lpq2

  # Get deployer logs
  kubectl logs -f $POD_ID
  ```

**Comment by zramsay** [comment] 2024-11-26 11:29
cc @BlackBlocks-io

**Comment by BlackBlocks-io** [comment] 2024-11-26 12:33
Same root cause as  https://github.com/LaconicNetwork/issues/issues/3
Fixed by using rpc and gql endpoints within the cluster.

**Closed as completed** 2024-11-26 13:39 UTC
